/*
 * Created on 2017-09-29 ( Time 14:21:28 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.CarRecord;
import org.demo.data.record.listitem.CarListItem;


//--- Services 
import org.demo.persistence.CarPersistence;
// import org.demo.business.service.impl.CarServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Car' management.
 */
@Path("/car")
public class CarResource extends AbstractResourceController {

	private CarPersistence carService = PersistenceServiceProvider.getService(CarPersistence.class);

	/**
	 * Constructor
	 */
	public CarResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all car entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<CarRecord> findAll() {
		logger.info("findAll()...");
		return carService.findAll();
	}

	/**
	 * Retrieves a car using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") int id) {
		logger.info("findById("+id+")...");
		CarRecord record = carService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new car.
	 * @param car car
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(CarRecord car) {
		logger.info("create()...");
		if ( carService.exists(car) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			CarRecord record = carService.create(car);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the car identified by the given id
	 * @param car car entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public CarRecord update(CarRecord car, @PathParam("id") int id) {
	public Response update(CarRecord car, @PathParam("id") int id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		car.setId( id );
		boolean updated = carService.update(car);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given car.
	 * @param car car entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(CarRecord car) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! carService.exists(car) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		CarRecord record = carService.save(car);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a car.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") int id) {
	public Response delete(@PathParam("id") int id) {
		logger.info("delete("+id+")...");
		// carService.deleteById(id);
		boolean deleted = carService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/cars-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<CarListItem> listItems() {
		logger.info("listItems()...");
		List<CarRecord> list = carService.findAll();
		List<CarListItem> items = new LinkedList<CarListItem>();
		for ( CarRecord car : list ) {
			items.add(new CarListItem( car ) );
		}
		return items;
	}

}
