/*
 * Created on 2017-09-29 ( Date ISO 2017-09-29 - Time 15:54:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.CarRecord;
import org.demo.persistence.CarPersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Car persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("CarPersistence")
public class CarPersistenceFake extends GenericFakeDAO<CarRecord> implements CarPersistence {

	/**
	 * Constructor
	 */
	public CarPersistenceFake() {
		super(CarRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private CarRecord newInstanceWithPrimaryKey(int id) {
		CarRecord record = new CarRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(CarRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(CarRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public CarRecord create(CarRecord record) {
		super.doCreate(record);
		return record;
	}

	@Override
	public boolean delete(CarRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		CarRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(CarRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		CarRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<CarRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public CarRecord findById(Integer id) {
        CarRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public CarRecord save(CarRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreate(record);
		}
        return record;
	}

	@Override
	public boolean update(CarRecord record) {
		return super.doUpdate(record);	
	}
}
