/*
 * Created on 2017-09-29 ( Date ISO 2017-09-29 - Time 15:54:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.DriverRecord;
import org.demo.persistence.DriverPersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Driver persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("DriverPersistence")
public class DriverPersistenceFake extends GenericFakeDAO<DriverRecord> implements DriverPersistence {

	/**
	 * Constructor
	 */
	public DriverPersistenceFake() {
		super(DriverRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private DriverRecord newInstanceWithPrimaryKey(int id) {
		DriverRecord record = new DriverRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(DriverRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(DriverRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public DriverRecord create(DriverRecord record) {
		super.doCreate(record);
		return record;
	}

	@Override
	public boolean delete(DriverRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		DriverRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(DriverRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		DriverRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<DriverRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public DriverRecord findById(Integer id) {
        DriverRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public DriverRecord save(DriverRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreate(record);
		}
        return record;
	}

	@Override
	public boolean update(DriverRecord record) {
		return super.doUpdate(record);	
	}
}
