/*
 * Created on 2017-09-29 ( Date ISO 2017-09-29 - Time 14:21:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.web.rest.commons;

import java.util.logging.Level;

/**
 * The logger level <br>
 * 
 * @author Telosys
 *
 */
public class LoggerLevel {

	// Set the logger level here :
	
	//public final static Level LEVEL = Level.OFF ;
	public final static Level LEVEL = Level.ALL ;
	
}
